module.exports = {
  imdbID: 'tt2724064',
  Title: 'Sharknado',
  Year: '2013',
  Rated: 'TV-14',
  Released: '11 Jul 2013',
  Runtime: '86 min',
  Genre: 'Action, Adventure, Comedy',
  Director: 'Anthony C. Ferrante',
  Writer: 'Thunder Levin',
  Actors: 'Ian Ziering, Tara Reid, John Heard, Cassandra Scerbo',
  Plot: 'When a freak hurricane swamps Los Angeles, nature\'s deadliest killer rules sea, land, and air.',
  Language: 'English',
  Country: 'USA',
  Awards: '1 win & 2 nominations.',
  Poster: 'https://m.media-amazon.com/images/M/MV5BOTE2OTk4MTQzNV5BMl5BanBnXkFtZTcwODUxOTM3OQ@@._V1_SX300.jpg',
  Ratings: [
    {
      Source: 'Internet Movie Database',
      Value: '3.3/10',
    },
    {
      Source: 'Rotten Tomatoes',
      Value: '82%',
    },
  ],
  Metascore: 'N/A',
  imdbRating: '3.3',
  imdbVotes: '40,724',
  Type: 'movie',
  DVD: '03 Sep 2013',
  BoxOffice: 'N/A',
  Production: 'NCM Fathom',
  Website: 'http://www.mtivideo.com/TitleView.aspx?TITLE_ID=728',
  Response: 'True',
}
